<a href="https://colab.research.google.com/github/dharmeshrohit/pydata-book/blob/main/pandas_series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is pandas
Pandas is fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the python programming language.

## pandas series
A pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [1]:
import numpy as np
import pandas as pd

## Series from lists

In [6]:
# string
country = ['India', 'Pakistan', 'USA', 'Nepal', 'Srilanka']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [9]:
# integers
runs = [13, 24, 56, 78, 100]

runs_ser = pd.Series(runs)

In [12]:
# custom index
marks = [67, 57, 89, 100]
subjects = ['maths', 'english', 'science', 'hindi']

pd.Series(marks, index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [14]:
# setting a name
marks = pd.Series(marks, index=subjects, name='joy ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: joy ke marks, dtype: int64

## Series from dict

In [15]:
marks = {
    'maths': 67,
    'english':57,
    'science':89,
    'hindi':100
}
marks_series = pd.Series(marks, name= 'Joy ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: Joy ke marks, dtype: int64

Series Attributes

In [16]:
# size
marks_series.size

4

In [17]:
# dtype
marks_series.dtype

dtype('int64')

In [18]:
# name
marks_series.name

'Joy ke marks'

In [22]:
# is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [23]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [24]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [25]:
# values
marks_series.values

array([ 67,  57,  89, 100])

Series using read_csv

In [32]:
# with one col
subs = pd.read_csv('/content/subs.csv').squeeze('columns')
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [39]:
# with 2 cols
vk = pd.read_csv('/content/kohli_ipl.csv', index_col='match_no').squeeze('columns')
vk

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [42]:
movies = pd.read_csv('/content/bollywood.csv', index_col='movie').squeeze('columns')
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

Series Methods

In [47]:
# head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [48]:
# head and tail
vk.head()

match_no
1     1
2    23
3    13
4    12
5     1
Name: runs, dtype: int64

In [50]:
vk.tail(10)

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [52]:
# sample
movies.sample(5)

movie
Kabir Singh                     Shahid Kapoor
Happy Husbands (2011 film)               Anay
Murari the Mad Gentleman         Sanjay Singh
Gulabi Gang (film)            Sampat Pal Devi
Katti Batti                      Suhaas Ahuja
Name: lead, dtype: object

In [55]:
# value_count -> movies
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [63]:
# sort_values -> inplace
vk.sort_values(ascending=False).head(5).values[0]

np.int64(113)

In [68]:
vk.sort_values(ascending=False)

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [72]:
# sort_idex -> movies
movies.sort_index(ascending=False)

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

### Series Maths Methods

In [73]:
# count
vk.count()

np.int64(215)

In [75]:
subs.sum()

np.int64(49510)

In [83]:
# mean -> median -> mode -> std -> var
print(subs.mean())
print(vk.median())
print(movies.mode())
print(subs.std())
print(subs.var())

135.64383561643837
24.0
0    Akshay Kumar
Name: lead, dtype: object
62.67502303725269
3928.1585127201556

In [84]:
# min/max
subs.min()

33

In [86]:
subs.max()

396

In [87]:
# describe
subs.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

### Series Indexing

In [88]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

0    12
1    13
2    14
3    35
4    46
5    57
6    58
7    79
8     9
dtype: int64

In [91]:
# negative indexing
x[1]

np.int64(13)

In [90]:
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [92]:
marks_series[-1]

/tmp/ipython-input-569294583.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks_series[-1]

np.int64(100)

In [95]:
# slicing
vk[5:14]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
12    38
13     3
14    11
Name: runs, dtype: int64

In [96]:
# negative slicing
vk[-5:]

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [97]:
moives[::2]

movie
Uri: The Surgical Strike                   Vicky Kaushal
The Accidental Prime Minister (film)         Anupam Kher
Evening Shadows                         Mona Ambegaonkar
Fraud Saiyaan                               Arshad Warsi
Manikarnika: The Queen of Jhansi          Kangana Ranaut
                                              ...
Raaz (2002 film)                              Dino Morea
Waisa Bhi Hota Hai Part II                  Arshad Warsi
Kaante                                  Amitabh Bachchan
Aankhen (2002 film)                     Amitabh Bachchan
Company (film)                                Ajay Devgn
Name: lead, Length: 750, dtype: object

In [100]:
# fancy indexing
vk[[1,3,23,5]]

match_no
1      1
3     13
23    19
5      1
Name: runs, dtype: int64

In [101]:
 # indexing with labels -> fancy indexing
 movies['2 States (2014 film)']

'Arjun Kapoor'